# Opt-in staging build. It never mutates the frozen upstream build tree.
enable_testing()
execute_process(COMMAND git -C "${CMAKE_SOURCE_DIR}/third_party/llama.cpp-omni" rev-parse HEAD
    OUTPUT_VARIABLE _edgeomni_upstream_commit OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _edgeomni_git_rc)
if(NOT _edgeomni_git_rc EQUAL 0 OR NOT _edgeomni_upstream_commit STREQUAL "19cc26967140407efe34006a355ab445b35b16ac")
    message(FATAL_ERROR "relocatable bundle requires llama.cpp-omni commit 19cc26967140407efe34006a355ab445b35b16ac")
endif()
set(EDGEOMNI_RELOCATABLE_BUNDLE_PREFIX "${CMAKE_BINARY_DIR}/bundle" CACHE PATH
    "Install prefix for the relocatable offline bundle")
set(EDGEOMNI_LLAMA_UPSTREAM_DIR "${CMAKE_SOURCE_DIR}/third_party/llama.cpp-omni")
set(EDGEOMNI_LLAMA_INCLUDE_DIR "${EDGEOMNI_LLAMA_UPSTREAM_DIR}/include" CACHE PATH "" FORCE)
set(EDGEOMNI_LLAMA_BUILD_DIR "${CMAKE_BINARY_DIR}/bin" CACHE PATH "" FORCE)

foreach(option BUILD_SHARED_LIBS GGML_CUDA LLAMA_BUILD_COMMON LLAMA_BUILD_TOOLS LLAMA_BUILD_EXAMPLES LLAMA_TOOLS_INSTALL)
    set(${option} ON CACHE BOOL "" FORCE)
endforeach()
foreach(option GGML_BACKEND_DL GGML_CUDA_NCCL LLAMA_BUILD_SERVER LLAMA_BUILD_APP LLAMA_BUILD_TESTS LLAMA_BUILD_UI)
    set(${option} OFF CACHE BOOL "" FORCE)
endforeach()
set(CMAKE_BUILD_RPATH_USE_ORIGIN ON CACHE BOOL "" FORCE)
set(CMAKE_INSTALL_PREFIX "${EDGEOMNI_RELOCATABLE_BUNDLE_PREFIX}" CACHE PATH "" FORCE)
set(CMAKE_INSTALL_BINDIR bin CACHE PATH "" FORCE)
set(CMAKE_INSTALL_LIBDIR lib CACHE PATH "" FORCE)
set(CMAKE_INSTALL_RPATH "\$ORIGIN/../lib" CACHE STRING "" FORCE)

add_subdirectory("${EDGEOMNI_LLAMA_UPSTREAM_DIR}" upstream)

set(_edgeomni_bundle_libs ggml ggml-base ggml-cpu ggml-cuda llama llama-common mtmd omni
    llama-batched-bench-impl llama-bench-impl llama-completion-impl llama-fit-params-impl
    llama-perplexity-impl llama-quantize-impl)
foreach(target IN LISTS _edgeomni_bundle_libs)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Required relocatable bundle library target is missing: ${target}")
    endif()
    set_target_properties("${target}" PROPERTIES INSTALL_RPATH "\$ORIGIN")
endforeach()
foreach(target IN ITEMS llama-embedding llama-tokenize)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Required relocatable bundle tool target is missing: ${target}")
    endif()
    set_target_properties("${target}" PROPERTIES INSTALL_RPATH "\$ORIGIN/../lib")
endforeach()
install(TARGETS llama-embedding RUNTIME DESTINATION bin)

add_subdirectory("${CMAKE_SOURCE_DIR}/runtime" runtime)
if(NOT TARGET edgeomni_vlm_service_host)
    message(FATAL_ERROR "Relocatable bundle requires EDGEOMNI_BUILD_BENCHMARK_TOOLS=ON")
endif()
set_target_properties(edgeomni_vlm_service_host PROPERTIES INSTALL_RPATH "\$ORIGIN/../lib")
install(TARGETS edgeomni_vlm_service_host RUNTIME DESTINATION bin)
install(CODE "file(MAKE_DIRECTORY \"${CMAKE_INSTALL_PREFIX}/configs\" \"${CMAKE_INSTALL_PREFIX}/models\" \"${CMAKE_INSTALL_PREFIX}/generated\")")
find_package(Python3 COMPONENTS Interpreter REQUIRED)
set(EDGEOMNI_MANIFEST_SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/RunBundleManifest.cmake")
configure_file("${CMAKE_SOURCE_DIR}/cmake/RunBundleManifest.cmake.in" "${EDGEOMNI_MANIFEST_SCRIPT}" @ONLY)
install(SCRIPT "${EDGEOMNI_MANIFEST_SCRIPT}")
